<?php
$billing = $this->getCart()->getBillingAddress();
?>
<form action="<?php echo $this->getUrl('*/Adminhtml_Order_Cart/Save'); ?>" method="POST">
    <?php echo $this->getBlockHtml('formkey'); ?>
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head fieldset-legend "><?php echo $this->getHeaderText() ?></h4>
        </div>
        <fieldset class="np">
            <div id="billing_address" class="order-choose-address">
                <br />
            </div>
            <div class="order-address" id="">
                <div class="content">
                    <div class="hor-scroll">
                        <table cellspacing="0" class="form-list">
                            <tbody>
                                <tr>
                                    <td class="label"><label for="order-billing_address_firstname">First Name <span class="required">*</span></label></td>
                                    <td class="value">
                                        <input id="order-billing_address_firstname" name="order[billing_address][firstname]" value="<?php echo $billing->getFirstname(); ?>" class=" required-entry input-text required-entry" type="text">
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label"><label for="order-billing_address_lastname">Last Name <span class="required">*</span></label></td>
                                    <td class="value">
                                        <input id="order-billing_address_lastname" name="order[billing_address][lastname]" value="<?php echo $billing->getLastname(); ?>" class=" required-entry input-text required-entry" type="text">
                                    </td>
                                </tr>

                                <tr>
                                    <td class="label"><label for="order-billing_address_street0">Street Address <span class="required">*</span></label></td>
                                    <td class="value">
                                        <div class="multi-input"><input id="order-billing_address_street0" name="order[billing_address][street][0]" value="<?php echo $billing->getStreet(); ?>" class="input-text required-entry" type="text">
                                        </div>

                                    </td>
                                </tr>
                                <tr>
                                    <td class="label"><label for="order-billing_address_city">City <span class="required">*</span></label></td>
                                    <td class="value">
                                        <input id="order-billing_address_city" name="order[billing_address][city]" value="<?php echo $billing->getCity(); ?>" class=" required-entry input-text required-entry" type="text">
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label"><label for="order-billing_address_country">country <span class="required">*</span></label></td>
                                    <td class="value">
                                        <input id="order-billing_address_city" name="order[billing_address][country]" value="<?php echo $billing->getCountryId(); ?>" class=" required-entry input-text required-entry" type="text">
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label"><label for="order-billing_address_region">State/Province <span class="required">*</span></label>
                                    </td>
                                    <td class="value">
                                        <input id="order-billing_address_city" name="order[billing_address][region]" value="<?php echo $billing->getRegion(); ?>" class=" required-entry input-text required-entry" type="text">
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label"><label for="order-billing_address_postcode">Zip/Postal Code <span class="required">*</span></label></td>
                                    <td class="value">
                                        <input id="order-billing_address_postcode" name="order[billing_address][postcode]" value="<?php echo $billing->getPostcode(); ?>" class=" required-entry input-text required-entry" type="text">
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="order-save-in-address-book">
                    <input name="order[save_in_address_book]" type="checkbox" id=" ?>save_in_address_book" value="1" />
                    <label for="save_in_address_book"><?php echo Mage::helper('order')->__('Save in address book') ?></label>
                </div>
                <div class="save">
                    <button class="button" onclick="mage.formSubmit()">Save Billing Address</button>
                </div>
            </div>

        </fieldset>
    </div>
</form>