<?php $shipping = $this->getShippingAddress(); ?>
<form action="<?php echo $this->getUrl('*/Adminhtml_Order_Cart/Save'); ?>" method="POST">
    <?php echo $this->getBlockHtml('formkey'); ?>
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head fieldset-legend "><?php echo $this->getHeaderText() ?></h4>
        </div>
        <fieldset class="np">
            <div id="shipping_address" class="order-choose-address">

                <br />

                <input type="checkbox" id="order-shipping_as_shipping" name="shipping_as_shipping" value="1" />
                <label for="order-shipping_as_shipping" class="no-float"><?php echo Mage::helper('order')->__('Same As Billing Address') ?></label>

            </div>
            <div class="order-address" id="">
                <div class="content">
                    <div class="hor-scroll">
                        <table cellspacing="0" class="form-list">
                            <tbody>
                                <tr>
                                    <td class="label"><label for="order-shipping_address_firstname">First Name <span class="required">*</span></label></td>
                                    <td class="value">
                                        <input id="order-shipping_address_firstname" name="order[shipping_address][firstname]" value="<?php echo $shipping->getfirstname(); ?>" class=" required-entry input-text required-entry" type="text">
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label"><label for="order-shipping_address_lastname">Last Name <span class="required">*</span></label></td>
                                    <td class="value">
                                        <input id="order-shipping_address_lastname" name="order[shipping_address][lastname]" value="<?php echo $shipping->getLastname(); ?>" class=" required-entry input-text required-entry" type="text">
                                    </td>
                                </tr>

                                <tr>
                                    <td class="label"><label for="order-shipping_address_street0">Street Address <span class="required">*</span></label></td>
                                    <td class="value">
                                        <?php $street = $shipping->getStreet();
                                        if (is_array($street)) {
                                            $street = $street[0] . " " . $street[1];
                                        }
                                        ?>
                                        <div class="multi-input"><input id="order-shipping_address_street0" name="order[shipping_address][street]" value="<?php echo $street; ?>" class="input-text required-entry" type="text">
                                        </div>

                                    </td>
                                </tr>
                                <tr>
                                    <td class="label"><label for="order-shipping_address_city">City <span class="required">*</span></label></td>
                                    <td class="value">
                                        <input id="order-shipping_address_city" name="order[shipping_address][city]" value="<?php echo $shipping->getCity(); ?>" class=" required-entry input-text required-entry" type="text">
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label"><label for="order-shipping_address_country">country <span class="required">*</span></label></td>
                                    <td class="value">
                                        <input id="order-shipping_address_city" name="order[shipping_address][country_id]" value="<?php echo $shipping->getCountryId(); ?>" class=" required-entry input-text required-entry" type="text">
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label"><label for="order-shipping_address_region">State/Province <span class="required">*</span></label>
                                    </td>
                                    <td class="value">
                                        <input id="order-shipping_address_city" name="order[shipping_address][region]" value="<?php echo $shipping->getRegion(); ?>" class=" required-entry input-text required-entry" type="text">
                                    </td>
                                </tr>
                                <tr>
                                    <td class="label"><label for="order-shipping_address_postcode">Zip/Postal Code <span class="required">*</span></label></td>
                                    <td class="value">
                                        <input id="order-shipping_address_postcode" name="order[shipping_address][postcode]" value="<?php echo $shipping->getPostcode(); ?>" class=" required-entry input-text required-entry" type="text">
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="order-save-in-address-book">
                    <input name="[save_in_address_book]" type="checkbox" id=" ?>save_in_address_book" value="1" />
                    <label for="save_in_address_book"><?php echo Mage::helper('order')->__('Save in address book') ?></label>
                </div>
                <div class="save">
                    <button class="button">Save Shipping Address</button>
                </div>
            </div>
        </fieldset>
    </div>
</form>