<form action="<?php echo $this->getUrl('*/Adminhtml_Order_Cart/Save') ?>" method="POST">
    <?php echo $this->getBlockHtml('formkey'); ?>
    <div class="page-create-order">
        <table cellspacing="0" width="100%">
            <tr>
                <td <?php if ($this->getCustomerId()) : ?>class="main-col" <?php endif; ?>>
                    <div id="order-search" class="order-search-items"><?php echo $this->getChildHtml('search') ?></div>
                    <div id="order-items"><?php echo $this->getChild('items_grid')->setCart($this->getCart())->toHtml(); ?></div>
                    <div id="order-addresses">
                        <div id="order-billing_address" class="box-left"><?php echo $this->getChild('billing_address')->setCart($this->getCart())->toHtml(); ?></div>
                        <div id="order-shipping_address" class="box-right"><?php echo $this->getChild('shipping_address')->setCart($this->getCart())->toHtml(); ?></div>
                    </div>
                    <div class="clear"></div>
                    <div id="order-methods">
                        <div id="order-billing_method" class="box-left payments"><?php echo $this->getChildHtml('billing_method') ?></div>
                        <div id="order-shipping_method" class="box-right"><?php echo $this->getChildHtml('shipping_method') ?></div>
                    </div>
                    <div class="clear"></div>
                </td>
            </tr>
        </table>
    </div>
</form>