<form action="<?php echo $this->getUrl('*/Adminhtml_Order_Cart/updateQuantity'); ?>" id="cart_form" method="POST">
<?php echo $this->getBlockHtml('formkey'); ?>
<div class="entry-edit">
<div class="entry-edit-head">
    <h4 class="icon-head head-cart"><?php echo $this->getHeaderText() ?></h4>
    <div class="form-buttons"><a href="#" class="scalable save button" onclick="showAction()">ADD Product</a></div>
</div>
<div class="grid" id="order-items_grid">
    <table cellspacing="0" class="data order-tables">
        <col width="25%" />
        <col width="25%" />
        <col width="25%" />
        <col width="25%" />
        <thead>
            <tr class="headings">
                <th class="no-link"><?php echo $this->helper('order')->__('Id') ?></th>
                <th class="no-link"><?php echo $this->helper('order')->__('Product') ?></th>
                <th class="no-link"><?php echo $this->helper('order')->__('Price') ?></th>
                <th class="no-link"><?php echo $this->helper('order')->__('Qty') ?></th>
                <th class="no-link"><?php echo $this->helper('order')->__('Action') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($items = $this->getCart()->getCartItems() as $key => $item) : ?>
                <tr>
                    <td><input type="text" name="update[cart_item_id]" value="<?= $item['cart_item_id'] ?>"></td>
                    <td><?= $this->getProductName($item['product_id']) ?></td>
                    <td><?= $item['price'] ?></td>
                    <td><input type="text" name="update[quantity]" value="<?= $item['quantity'] ?>" id=""></td>
                    <td><button class="submit" name="delete" value="<?= $item['cart_item_id'] ?>" onclick="deleteItem()">Delete</button></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
        <tfoot>
            <tr>
                <td class=" a-left" colspan="2"><?php echo $this->helper('order')->__('Total %d product(s)',count($items))?></td>
                <td class="a-right"><?php echo $this->helper('order')->__('Subtotal:') ?></td>
                <td class="price"><strong><?php echo $this->getCart()->getSubtotal(); ?></strong></td>
                <td class="price"><strong><?php echo $this->getCart()->getDiscountAmount();  ?></strong></td>
                <td class="price"><strong><?php echo $this->getCart()->getSubtotalWithDiscount();  ?></strong></td>
                <td colspan="2"><div class="form-buttons"><?php echo $this->getButtonHtml() ?></div>
                </td>
            </tr>
        </tfoot>
    </table>
</div>
<table cellspacing="0" width="100%">
    <col width="50%" />
    <col width="50%" />
</table>
<br />
</div>
</div>
</form>